### ISSUE TITLE
执行 npm run extract-intl 报错

### ISSUE THREAD

**Issue by wzxm** [boxcc/umi-pro#1]
![image](https://user-images.githubusercontent.com/13127730/43657427-6304a0ca-9788-11e8-8bc9-438f37f6e1ac.png)
![image](https://user-images.githubusercontent.com/13127730/43657431-6862fb52-9788-11e8-9b0f-67267cdf8ea4.png)

**Comment by boxcc** [comment]
babel版本问题, 已经修复了

**Comment by wzxm** [comment]
感谢。
